apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: packageserver-pdb
  namespace: openshift-operator-lifecycle-manager
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: packageserver
